In [1]:
from src.data import Dataloader
import pandas as pd
import os



In [2]:
# Const
DATA_PATH = os.path.abspath('data/clean/')
VAL_START_DATE = int(pd.Timestamp('2023-12-20').timestamp() * 1e9)  
TEST_START_DATE = int(pd.Timestamp('2024-12-20').timestamp() * 1e9)



In [3]:
data_loader = Dataloader(DATA_PATH)
timeseries_data = data_loader.from_csv("aave.csv", feat_columns = ['Close','High','Low', 'Open'])

train_data, val_test_data = timeseries_data.split(VAL_START_DATE)
val_data, test_data = val_test_data.split(TEST_START_DATE)

print(len(train_data))
print(len(val_data))
print(len(test_data))

count = 0
for time, feat,binary_labels ,regression_labels  in train_data:
    count += 1
    print(time)
    print(feat)
    print(binary_labels)
    print(regression_labels)
    if count == 3:
        break


799
366
382
tensor(1633996800000000000)
tensor([283.8271, 290.7943, 271.1401, 290.7943], dtype=torch.float64)
tensor(1., dtype=torch.float64)
tensor(297.6792, dtype=torch.float64)
tensor(1634083200000000000)
tensor([297.6792, 300.6757, 282.3102, 283.9403], dtype=torch.float64)
tensor(1., dtype=torch.float64)
tensor(303.5018, dtype=torch.float64)
tensor(1634169600000000000)
tensor([303.5018, 309.2618, 293.6589, 297.3920], dtype=torch.float64)
tensor(0., dtype=torch.float64)
tensor(300.9591, dtype=torch.float64)
